CREATE TABLE CLIENTE (
	ID VARCHAR(255) PRIMARY KEY,
	NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
	ID VARCHAR(255) PRIMARY KEY,
	DESCRICAO VARCHAR(100),
	PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
	ID VARCHAR(255) PRIMARY KEY,
	CLIENTE_ID VARCHAR(255) REFERENCES CLIENTE (ID),
	DATA_PEDIDO TIMESTAMP,
	TOTAL_PEDIDO NUMERIC(20, 2)
);

CREATE TABLE ITEM_PEDIDO (
	ID VARCHAR(255) PRIMARY KEY,
	PEDIDO_ID VARCHAR(255) REFERENCES PEDIDO (ID),
	PRODUTO_ID VARCHAR(255) REFERENCES PRODUTO (ID),
	QUANTIDADE INTEGER
);